In [86]:
import numpy as np

# Arrays Operations

## Indexing

In [87]:
a = np.arange(1,10,dtype="int8").reshape(3,3)

In [88]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [89]:
a[[0,1],[1,2]] 

array([2, 6], dtype=int8)

In [90]:
a[0:,2]

array([3, 6, 9], dtype=int8)

In [91]:
a[:,2]

array([3, 6, 9], dtype=int8)

In [92]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

change array element

In [93]:
a[1,1]=300
a

array([[ 1,  2,  3],
       [ 4, 44,  6],
       [ 7,  8,  9]], dtype=int8)

## Arithmetic operations

In [94]:
# add python list
[1,2,3] + [4,5]

[1, 2, 3, 4, 5]

In [95]:
# add np arrays: element wise
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [96]:
a1+a2

array([5, 7, 9])

In [97]:
a1*a2

array([ 4, 10, 18])

In [98]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [99]:
a1

array([1, 2, 3])

In [100]:
a1*3

array([3, 6, 9])

In [101]:
a1%2

array([1, 0, 1])

In [102]:
a1

array([1, 2, 3])

In [103]:
a1.mean()

2.0

### Logical Operations

In [104]:
a1

array([1, 2, 3])

In [105]:
a2

array([4, 5, 6])

In [106]:
a1 < a2

array([ True,  True,  True])

In [107]:
a1[[True, False, False]]

array([1])

In [108]:
a1

array([1, 2, 3])

In [109]:
even_mask = a1%2==0
even_mask

array([False,  True, False])

In [110]:
a1[even_mask]

array([2])

In [111]:
# get odd elements:
a1[a1%2!=0]

array([1, 3])

In [112]:
a1

array([1, 2, 3])

In [113]:
choices = np.array([0,1,2])

In [114]:
a1<2 

array([ True, False, False])

In [115]:
a

array([[ 1,  2,  3],
       [ 4, 44,  6],
       [ 7,  8,  9]], dtype=int8)

In [116]:
res = np.logical_and(a>3,a<40)
a_new = a[res]
a_new

array([4, 6, 7, 8, 9], dtype=int8)